### ISSUE TITLE
Spamming buckets of water

### ISSUE THREAD

**Issue by ninjakidic** [oiisamiio/TerrariaDedicatedServerGui#3]
If I start getting water or lava in buckets fast it activates the cheat protection and forces me off my OWN game.  Please fix this as this is obviously not cheating. 
I am not trying to sound mad on this comment =)

**Comment by oiisamiio** [comment]
Hi, don't know what you mean. Could you show me a Video on youtube or elsewhere?

**Comment by ninjakidic** [comment]
Well it only did it like 5 times on me in my server (was making sure it was a bug). I cant really youtube it either  i could try the step recorder.....maybe. But like I said, when you gather buckets of water really fast (picking it up), when the cheat protection is on, getting that water seems to activate the protection and kicks me out of the game.

**Comment by oiisamiio** [comment]
This Project is just an GUI for Terraria Dedicated Server. So Sorry, cant do anything for you. Just turn off Cheat Protection...
