### ISSUE TITLE
Console buttons not working

### ISSUE THREAD

**Issue by Pipboy7** [oiisamiio/TerrariaDedicatedServerGui#4]
The buttons within the console tab are not working making it unable to safely shutdown the server

**Comment by oiisamiio** [comment]
confirmed:
looks like StandardInput.WriteLine() not working anymore. Try to fix this next time.

**Comment by Eloncase** [comment]
it seems to be an encoding issue
```cs
var InputStream = new StreamWriter(pController.StandardInput.BaseStream, Encoding.Unicode);
InputStream.WriteLine("exit");
InputStream.Flush();
```
doing so seems to be working

**Comment by oiisamiio** [comment]
Special Thanks, will Test this next

**Comment by oiisamiio** [comment]
Perform @Eloncase s Solution with StreamWriter. Enconding issue fixed
