### ISSUE TITLE
how to find the ip?

### ISSUE THREAD

**Issue by waie111** [oiisamiio/TerrariaDedicatedServerGui#6]
it can switch on but i have to click no on the world maps, and where can the ip be found? i cant find it

**Comment by oiisamiio** [comment]
Select the World Map Path under Settings otherwise create a new Map. Your IP Address is located on left bottom.

![sample](https://user-images.githubusercontent.com/4339308/107128455-23491880-68be-11eb-8eeb-d39c779c0370.png)
